### ISSUE TITLE
Potential mismatch in terminology between 4.2 and 4.3 on cert checks

### ISSUE THREAD

**Issue by mstojens** [ietf-wg-add/draft-ietf-add-ddr#100]
Section 4.2, verified, calls out the entire cert check for validation, but section 4.3, opportunistic, only talks about skipping the IP validation. 

It has gone without saying that these are equivalent because the IP is the only thing about the cert being validated, but for implementors, does this mean they can skip the entire cert validation process (meaning the connection will be used even if other errors occur, such as the cert being expired)?

I assume yes (no cert checking of any kind), but we should be specific.

**Comment by tfpauly** [comment]
I think it's up to implementations. If I look at the opportunistic profile in RFC 7858, it say:

> With such a discovered DNS
>    server, the client might or might not validate the resolver.

I think we should point to that and explain that it's open to the client to determine how opportunistic it wants to be
