### ISSUE TITLE
Clarify behavior with lack of v4/v6 hints

### ISSUE THREAD

**Issue by tfpauly** [ietf-wg-add/draft-ietf-add-ddr#2]
From Eliot Lear:

The draft currently reads:

 When responding to these special queries for
   "dns://resolver.arpa", the SVCB records SHOULD contain at least one
   "ipv4hint" and/or "ipv6hint" keys. 

What happens when neither hint is present?  The client should just query the local infrastructure, right?  You almost say that, but not quite.

**Comment by mstojens** [comment]
This is an interesting case. There are threat model implications to always querying the template name elsewhere. 

I will draft up something to address that includes a commentary on the implications for the client.
