### ISSUE TITLE
removing an attempt to define Equivalence

### ISSUE THREAD

**Issue by mglt** [ietf-wg-add/draft-ietf-add-ddr#20]
I am not sure we need to introduce "Equivalence" nor to develop who is operating the resolvers - especially as many entities may be involved in the operation of a resolver. 

I am not sure we need to introduce Equivalence. If so I would propose the following text:

OLD:
"Equivalence" in this context means that the resolvers are operated by the same entity; for example, the resolvers are accessible on the same IP address, or there is a certificate that claims ownership over both resolvers.

NEW:
"Equivalence" in this context means that Encrypted and Unencrypted resolvers are either accessible on the same IP address, or there is a certificate that claims ownership over both resolvers.

If Equivalence is not introduced - which I prefer -I would propose the following text:

NEW:
In this context the discovery process ensures that Encrypted and Unencrypted resolvers are either accessible on the same IP address, or there is a certificate that claims ownership over both resolvers.

**Comment by mstojens** [comment]
I agree that we do not need to introduce "equivalence" in this document. It is a remnant of the DEER draft DDR is based on.

Per WG discussion, we want to use the term "designation" to describe the relationship between the unencrypted resolver and the encrypted resolver to which the client is transferring. I'm editing accordingly.

I have also added references to the possibility of multiple "entities" as that is definitely possible.

(PR coming later tonight)

**Comment by mglt** [comment]
good.
