### ISSUE TITLE
DDR section 4.1

### ISSUE THREAD

**Issue by tfpauly** [ietf-wg-add/draft-ietf-add-ddr#3]
From Eliot Lear:

Can you explain the following statement?

and that IP address is a private address
   (such as those defined in [RFC1918]

I ask because it appears that you are using private addresses as some sort of security property.  I recommend against that, not least of which is that end systems that are likely to deploy this stuff will have a wide ranging mishmosh of addressing plans, and of course, private network addresses don’t really have any positive security properties to speak of.

The only aspect I can see is that one really has to be quite careful of including private network addresses in certificates.  Of course, public trust anchors won’t allow it, but even private ones will have some difficulty.  Your average bank might have multiple overlapping zones of trust - it’s a pretty hairy scene.

**Comment by mstojens** [comment]
The intent of that section is to say that "if you were going to send this local IP address unencrypted traffic anyway, using encryption to that same IP address is a net improvement to the threat model." It certainly was not meant to imply that private addresses could be verified via the TLS cert SAN mechanism used for public addresses.

I can try to rephrase this section to be more accurate. Please comment again if I missed the point.

**Comment by mstojens** [comment]
With the PR merged, I am closing this issue.
