### ISSUE TITLE
Which name is authenticated?

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-add/draft-ietf-add-ddr#41]
> In order to be considered an authenticated Designated Resolver, the TLS certificate presented by the Designated Resolver MUST contain both the domain name (from the SVCB answer) and the IP address of the designating Unencrypted Resolver within the SubjectAlternativeName certificate field. 

When this says "the domain name (from the SVCB answer)", what does it refer to?  Does this refer to the TargetName of a SVCB record?

If so, which TargetName?  If I query for SVCB records at _dns.resolver.arpa, I might get an arbitrary number of AliasMode SVCB RRs, which might each lead to some number of other AliasMode SVCB RRs on the way to a ServiceMode SVCB RR.  That might be a lot of options.

**Comment by tfpauly** [comment]
@bemasc thanks for the change in the SVCB-DNS draft. That certainly helps make this more consistent. With that change, then we no longer need to have any special case in DDR for making sure that both the address and the name used in the HTTP authority are the covered in the cert, since they'll be the same.

**Comment by tfpauly** [comment]
Going off of Tommy's point, another reason it would be incorrect to force the HTTP host or TLS SNI to be an address is that this wouldn't work for the "opportunistic" case, where the address is shared but not covered by the cert. 

So I think we should remove the line about checking the hostname in the cert, but also explain how to get the name from the SVCB record. Initially, the first name we get back in the chain sounds like the right answer.

**Comment by tfpauly** [comment]
@bemasc I wasn’t suggesting anything about certificate validation. Rather, that for opportunistic mode, we should provide guidance about which hostname to use in the SNI and HTTP authority.

**Comment by ekr** [comment]
Too follow up what I said in the meeting:

 What if you have a situation where a DoH server is co-located with a hosting system, e.g., "doh.example.com" and "ekr.example.com" and the CDN just steers based on Host: header. So what I do is I stand up a DoH server on "ekr.example.com" that produces lying responses. Then I arrange for your SVCB record to have the name "ekr.example.com" and I have persuaded the client to accept responses from my invalid server.
