### ISSUE TITLE
Include IP address in SNI as ip6.arpa/inaddr.arpa

### ISSUE THREAD

**Issue by enygren** [ietf-wg-add/draft-ietf-add-ddr#49]
Given the requirements for the certificate to include a given IP address, clients (must?) send the IP address they are expecting to see in the certificate in the SNI, if this is the primary thing they will be validating there.
I'd propose we encode this in the same way as rfc8738 section 6 does, using ip6.arpa/inaddr.arpa:
https://datatracker.ietf.org/doc/html/rfc8738#section-6

A sample use-case where this is necessary is if a managed service provider is operating a DoH service on behalf of an ISP.  The Managed Service Provider's DoH server will need to know which of its customers' DNS servers to serve up a certificate for without needing to provision an IPv4 address per cert.  Putting multiple IPs from different orgs onto the same SAN cert also doesn't seem viable.

**Comment by tfpauly** [comment]
The WG discussion covered the fact that SNI IP addresses aren’t generally supported right now, so I don’t think it’s appropriate to add such a requirement.

**Comment by enygren** [comment]
Using an encoding of the IP address as  ip6.arpa/inaddr.arpa to send in SNI should be generally supported --- it just requires that the client pass that SNI hostname to the library.  It's sending the IP address itself which isn't supported, but as discussed in the ADD WG session the rfc8738 hack provides a work-around.

**Comment by mstojens** [comment]
Closing based on WG discussion (on thread here and in 112 where we closed on the original resolver's IP address as used by the client).
