### ISSUE TITLE
Include TLS cert fingerprint(s) as SvcParam, at least for Opportunistic Discovery

### ISSUE THREAD

**Issue by enygren** [ietf-wg-add/draft-ietf-add-ddr#50]
Having a SvcParam that expresses the expected TLS cert fingerprint(s) would make the story stronger for Opportunistic Discovery.  To improve the story here, it might be reasonable to require the clients to use TCP rather than UDP to their unencrypted resolvers?  This creates a cryptographic linkage between the response from the unencrypted resolver and the designated resolver, so still vulnerable to active attacks on that path.

Clients would need a way to express this in the SNI to allow the server to send the proper certificate (eg, in an underscore-prefixed label?).

It may be worth considering whether this would be adequate to alleviate the need for the "Designated Resolver MUST contain the IP address of the designating Unencrypted Resolver" requirement in some circumstances, such as if the Designated Resolver is on the same subnet as the client.  One major driver here is that IPv6 forwarding resolvers on the local network will typically be in public and not private address space, and it would be unfortunate if they were left out.

From a threat model perspective:
* Using a TLS cert fingerprint leaves clients still vulnerable to active on-path attacks between the client and their unencrypted resolvers.
* Using IP address certificates is only as good as the validation story for IP address certificates, and for DV certs may also be vulnerable to active on-path attacks between a validator and the unencrypted resolver, although there is visibility in a CT log.
* Both cases are also only as good as the security of resolver configuration (often via DHCP(v6) and/or ICMPv6) which is often also vulnerable to active on-path attacks.
* Taking this approach reduces risk exposure for clients between the client and the designated resolver.
* This remains vulnerable to attacks where a forwarding resolver blindly forwards the DDR lookup over an insecure channel.

**Comment by tfpauly** [comment]
This is an interesting idea, but feels better as an extension/addition?

**Comment by bemasc** [comment]
@evansrg and I just published [a draft](https://datatracker.ietf.org/doc/html/draft-rebs-dnsop-svcb-dane-00) on how to combine TLSA with SVCB.  For DANE-capable clients and signed TargetNames, I think that draft provides roughly the kind of security guarantee that is sought here.

Putting key fingerprints in the SVCB record sounds pretty scary to me, because it creates a high risk of "accidental pinning" when the SVCB record is not owned by the origin.

**Comment by mstojens** [comment]
I generally think that this violates WG discussion regarding using entropy in the SVCB record to authenticate the designated endpoint (else we could go back to the original behavior where we check for the domain name of the DoH URI template).

+1 to exploring this as a separate extension to DDR. @enygren does the draft Ben suggested look appropriate?

**Comment by mstojens** [comment]
Closing per discussion above.
