### ISSUE TITLE
Reiterate handling of unknown mandatory SVCB parameters 

### ISSUE THREAD

**Issue by tfpauly** [ietf-wg-add/draft-ietf-add-ddr#52]
We should clarify that if a client doesn’t understand a mandatory parameter in an SVCB record, it MUST NOT use it as normal DoT/DoH, since it could be misinterpreting the meaning.

**Comment by enygren** [comment]
Concrete example might be with:

"mandatory=foo,dohpath foo=[...] alpn=h2 dohpath=[...]" 

Where clients which don't know how to handle "foo" must ignore that RR in the RRset, which might also contain other SVCB RRs for just DoH.
