### ISSUE TITLE
Need a reminder about NXDOMAIN

### ISSUE THREAD

**Issue by bemasc** [ietf-wg-add/draft-ietf-add-ddr#58]
Resolvers will normally return NXDOMAIN for queries that don't exist, and caches are permitted to treat this as an indication that no records of any type exist at the zone (RFC 8020).  That means that it isn't enough for resolvers to synthesize a SVCB response for _dns.resolver.arpa: they also have to synthesize a NOERROR response for any other QTYPE on that name.  The draft should probably mention that.

Credit to @hazelesque for noticing this.

**Comment by tfpauly** [comment]
@bemasc agreed that we could note this, but it's also expected that a client wouldn't be sending out queries for other types on resolver.arpa, right? In practice, I'm not sure how this would happen.

**Comment by bemasc** [comment]
Yes, but if a cache is shared by multiple clients (be they distinct devices on a network or even distinct apps on a device), a single client could issue a query that causes the shared cache to remember the NXDOMAIN answer.  That's a problem whether the source of the query is malicious or just weird.

**Comment by tfpauly** [comment]
Fair, so this could be accidental or malicious fallout, not a normal occurrence.

**Comment by awfulhak** [comment]
I'd suggest that there should also be a reference to RFC 6303 section 3 - ```resolver.arpa``` should be considered a "locally resolved domain".

**Comment by tfpauly** [comment]
Closed with #61
