### ISSUE TITLE
The certificate should chain to a trust anchor

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-add/draft-ietf-add-ddr#66]
> In order to be considered a verified Designated Resolver, the TLS certificate presented by the Designated Resolver MUST contain the IP address of the designating Unencrypted Resolver in a subjectAltName extension. 

That's it apparently.  No mention of RFC 6125(bis).  On that basis, a self-signed certificate suffices.

This is something that recently came up on the mailing list and apparently current deployments are validating based on WebPKI trust anchors in addition to checking for the iPAddress subjectAltName.  So it's not as bad as this allows.  Maybe that should be written down.

The same problematic text is found in Section 4.2 and Section 5.

**Comment by tfpauly** [comment]
@martinthomson do you have a suggestion about the right way to explain the trust anchor use here? Any text we can model after?

**Comment by bemasc** [comment]
s/MUST contain/MUST prove authority over/ ?

**Comment by tfpauly** [comment]
@martinthomson take a look at the proposed text
