### ISSUE TITLE
Modifying dohpath

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-add/draft-ietf-add-ddr#70]
What does this mean?

> DoH resolvers that allow discovery using DNS SVCB answers over unencrypted DNS MUST NOT provide differentiated behavior based on the HTTP path alone, since an attacker could modify the "dohpath" parameter.

I'm struggling to work out what this might mean for someone operating a DoH server.

Does this mean that rewriting "/doh{?dns}" to "/~attacker/abcdef{dns}abcdef.txt" is considered something that the DoH resolver needs to identify and recover from?

Or, is this more narrow in that a DoH server cannot offer two different services on a referred endpoint with different treatment policies?

In the former case, the attacker can deny service by modifying the "dohpath".  In the latter case, the attacker gets to choose which of the two services is used.

I think that you want to lump the former under the general DoS risk.  But the latter implies something very specific in terms of action on the part of the resolver operator.  They cannot offer more than one DoH service on the same IP address (where DDR doesn't give them any virtual hosting capabilities via SNI) or hostname (where it does).  You might need to be a lot clearer about that.

**Comment by tfpauly** [comment]
This is about the latter case — if the resolver offers two very different services on different paths, the attacker would get to choose which service is used.

That doesn't mean you can't offer different services on the same resolver IP address, but something else would need to be different other than the path — like, for DDR clients, they'll be using the IP address, but some client that was configured with a specific service might use a specific hostname too.

**Comment by tfpauly** [comment]
See also: https://github.com/ietf-wg-add/draft-ietf-add-ddr/issues/47

**Comment by tfpauly** [comment]
@martinthomson please see #76
